### ISSUE TITLE
What is the permission SYSTEM_ALERT_WINDOW needed/used for?

### ISSUE THREAD

**Issue by IzzySoft** [bugsdev2/bookaccio#1]
v0.0.7 just reached IzzyOnDroid, and the scanner reported:

    ! repo/com.bugsdev2.bookaccio_7.apk declares sensitive permission(s):
      android.permission.SYSTEM_ALERT_WINDOW

As this permission is not listed in the app description, could you please clarify what it is needed/used for? Thanks in advance!

**Comment by IzzySoft** [comment]
Thanks! And as for the pre-edit message: sure it's good to have it in the app description! With IzzyOnDroid, there is a second place, but that's only shown in the web repo browser:

![image](https://github.com/user-attachments/assets/e7b55988-848b-4675-8fcc-8626f5d7c982)

:wink:

**Comment by bugsdev2** [comment]
Understood. Thank you. :smiley:

**Comment by IzzySoft** [comment]
@bugsdev2 on 2024-12-20, the scanner yielded `android.permission.CAMERA android.permission.RECORD_AUDIO`. Camera is clear (barcode scanner), but what for does the app need access to the microphone?

**Comment by bugsdev2** [comment]
> @bugsdev2 on 2024-12-20, the scanner yielded `android.permission.CAMERA android.permission.RECORD_AUDIO`. Camera is clear (barcode scanner), but what for does the app need access to the microphone?

Hi, could you mention the line. I checked my androidmanifest.XML file and did not find record audio permission being asked.

**Comment by IzzySoft** [comment]
I didn't check where it was declared, it's what e.g. `aapt d badging *.apk` reports. So it might be dragged in by some dependency. And it seems this is already solved: 0.2.0 no longer has it, it was only in 0.1.0:

```
package: name='com.bugsdev2.bookaccio' versionCode='100' versionName='0.1.0' platformBuildVersionName='14' platformBuildVersionCode='34' compileSdkVersion='34' compileSdkVersionCodename='14'
sdkVersion:'23'
targetSdkVersion:'34'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='com.bugsdev2.bookaccio.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
application-label:'Bookaccio'
```

So apologies for the noise: I was AFK for 11 days and working the backlog after my return, so this popped up and I reported it to you. I should have cross-checked before if a later update had already solved it, as it was the case here. :bow:

**Comment by bugsdev2** [comment]
Ah. Okay. No problem. :smile:

**Comment by IzzySoft** [comment]
News of the day:

    ! repo/com.bugsdev2.bookaccio_300.apk declares sensitive permission(s):
      android.permission.READ_MEDIA_IMAGES android.permission.READ_MEDIA_VIDEO

I guess `READ_MEDIA_IMAGES` is for the new "feature whereby user can choose book cover from local storage" – but video?

**Comment by bugsdev2** [comment]
Hmm... 

My android manifest file contains only these permissions. I dunno how the others are being added. 

<uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

Could you tell me where these permissions are?

**Comment by IzzySoft** [comment]
Same as above: I can't. I can only see what the final APK's `AndroidManifest.xml` has. But you might know what changed between the previous release and this one, and thus find out what might have dragged in the permission? Especially with Expo, I don't even have a clue what to look at.

**Comment by bugsdev2** [comment]
Hmm... So, should I add READ_MEDIA_IMAGES in the description?
If so, I'll do that.

As for READ_MEDIA_VIDEO, I dunno why its being pulled. Because for the book cover selection, I can view only images not videos. I have a screenshot prevention module as well which also prevents screen recording. Could it be related to that? Will have to look into it.

**Comment by IzzySoft** [comment]
> Hmm... So, should I add READ_MEDIA_IMAGES in the description?

If it's intended to be used, that makes sense, yes.

> As for READ_MEDIA_VIDEO, I dunno why its being pulled.

Must be from some dependency, as your `AndroidManifest.xml` here doesn't have it. If you suspect some module, you could check its manifest (or source), otherwise I don't know.

Thanks for checking!
