### ISSUE TITLE
ISO dates in the name of the backup file

### ISSUE THREAD

**Issue by alensiljak** [bugsdev2/bookaccio#3]
Hi!
I would appreciate if it was possible to use ISO dates in the name of the backup file, in order to have them sorted automatically. Whether by changing the default filename or allowing for the customisation, it doesn't matter.
Thanks for the great app!

**Comment by bugsdev2** [comment]
Will implement it in the next update. :+1:  

So glad that you like using my app. :smile:

**Comment by alensiljak** [comment]
Thanks a lot! The app is awesome. I might share some more ideas after I've been using it a bit longer.

**Comment by bugsdev2** [comment]
> I might share some more ideas after I've been using it a bit longer.

That would be nice. Do suggest. :+1:

**Comment by bugsdev2** [comment]
I've made the suggested change. 
Using of ISO dates in export file is set by default.
It will be available in the upcoming release: 
Bookaccio v0.2.0
