### ISSUE TITLE
Alternative app variant (internet and Google free)

### ISSUE THREAD

**Issue by serrq** [bugsdev2/bookaccio#6]
I have no need for Google APIs and internet permission.
Because I add all my books manually.

Is it possible get a separate version internet and Google free? (Arm64 v8a)

**Comment by bugsdev2** [comment]
A question. Do you need a different variant for that? I mean. The option to add manually is already there.

**Comment by bugsdev2** [comment]
> A different variant of your app without Google APIs and internet permission.
> 
> To upload the book cover art I need of a file picker action through SAF or local gallery (both).

Yes, I understood your request. My question was is there a need for a variant without all those. I can add the File picker for book cover. Would that fix the issue?

I'm asking this because it'll be more work to maintain different variants of the app.

**Comment by bugsdev2** [comment]
I understand. But, I'm sorry to say that, at the moment, maintaining a different variant of the app is a bit too much work from my end. I hope you understand.

**Comment by bugsdev2** [comment]
> Could add a local file picker for book cover art?

This I can do. 👍
And thanks for understanding.

**Comment by bugsdev2** [comment]
> I mean with SAF (without permissions request).

Okay.
